# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33c1961ffe5ea384ed99b387dca72350246890db15ed6cad75987c2bce3c5b9be64683894d7bd4d40da013eab14060992bebc3bdd860f2e315f914f06c778297

test:
  secret_key_base: fd9dbc0518bee1c7d2b96b8e7d40ef5e5f3f465e8f1816bbdd2c7aff52ffc4167ddb35f44a00f5646bde9caec26da00495cf52526e56cf6f02017749d56bf333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
